org: crowdedturkey
console: true
service: u-go-alefrank-challenge-backend

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    MONGO_DB_URI: ${env:MONGO_DB_URI}
    NODE_ENV: production

functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
